name: demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2  # Sử dụng thư viện HTTP
  shared_preferences: ^2.0.13  # Sử dụng thư viện shared_preferences
  intl: ^0.18.0  # Thêm thư viện intl cho DateFormat

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  async: ^2.11.0
  google_fonts: ^6.2.1
  path_provider: ^2.0.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Thêm thư mục assets để Flutter nhận diện các hình ảnh
